# Generated by Django 2.2.15 on 2020-10-01 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foia', '0074_auto_20200924_1225'),
        ('foia', '0077_auto_20200911_0945'),
    ]

    operations = [
    ]
